name: Laravel

on:
  push:
    branches: [ "main","jala-dev" ]
  pull_request:
    branches: [ "main","jala-dev" ]
jobs:
  laravel-tests:

    runs-on: windows-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer, php-cs-fixer
        extensions: mbstring, xml, ctype, json, pdo, bcmath, fileinfo
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Update Composer
      run: composer update
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create database directory (Linux/macOS)
      if: runner.os != 'Windows'
      run: mkdir -p database
    - name: Create database directory (Windows)
      if: runner.os == 'Windows'
      run: |
          if (!(Test-Path "database")) { New-Item -ItemType Directory -Path "database" -Force }
      shell: pwsh 
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: database/database.sqlite
      run: php artisan test
